// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_beta_knn_single
List cpp_beta_knn_single(IntegerMatrix species_pa, NumericMatrix dist_mat, int seed, bool use_jaccard);
RcppExport SEXP _spacc_cpp_beta_knn_single(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedSEXP, SEXP use_jaccardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type use_jaccard(use_jaccardSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_beta_knn_single(species_pa, dist_mat, seed, use_jaccard));
    return rcpp_result_gen;
END_RCPP
}
// cpp_beta_knn_parallel
List cpp_beta_knn_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_seeds, bool use_jaccard, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_beta_knn_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP use_jaccardSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_jaccard(use_jaccardSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_beta_knn_parallel(species_pa, dist_mat, n_seeds, use_jaccard, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// calc_coverage
double calc_coverage(NumericVector abundances);
RcppExport SEXP _spacc_calc_coverage(SEXP abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_coverage(abundances));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_coverage_single
List cpp_knn_coverage_single(IntegerMatrix species_mat, NumericMatrix dist_mat, int seed);
RcppExport SEXP _spacc_cpp_knn_coverage_single(SEXP species_matSEXP, SEXP dist_matSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_mat(species_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_coverage_single(species_mat, dist_mat, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_coverage_parallel
List cpp_knn_coverage_parallel(IntegerMatrix species_mat, NumericMatrix dist_mat, int n_seeds, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_knn_coverage_parallel(SEXP species_matSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_mat(species_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_coverage_parallel(species_mat, dist_mat, n_seeds, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_at_coverage
NumericVector interpolate_at_coverage(NumericVector richness, NumericVector coverage, NumericVector targets);
RcppExport SEXP _spacc_interpolate_at_coverage(SEXP richnessSEXP, SEXP coverageSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type richness(richnessSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coverage(coverageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_at_coverage(richness, coverage, targets));
    return rcpp_result_gen;
END_RCPP
}
// cpp_distance_matrix
NumericMatrix cpp_distance_matrix(NumericVector x, NumericVector y, std::string method);
RcppExport SEXP _spacc_cpp_distance_matrix(SEXP xSEXP, SEXP ySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_distance_matrix(x, y, method));
    return rcpp_result_gen;
END_RCPP
}
// calc_hill_number
double calc_hill_number(NumericVector abundances, double q);
RcppExport SEXP _spacc_calc_hill_number(SEXP abundancesSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_hill_number(abundances, q));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_hill_single
NumericMatrix cpp_knn_hill_single(IntegerMatrix species_mat, NumericMatrix dist_mat, int seed, NumericVector q_values);
RcppExport SEXP _spacc_cpp_knn_hill_single(SEXP species_matSEXP, SEXP dist_matSEXP, SEXP seedSEXP, SEXP q_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_mat(species_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q_values(q_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_hill_single(species_mat, dist_mat, seed, q_values));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_hill_parallel
List cpp_knn_hill_parallel(IntegerMatrix species_mat, NumericMatrix dist_mat, int n_seeds, NumericVector q_values, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_knn_hill_parallel(SEXP species_matSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP q_valuesSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_mat(species_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q_values(q_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_hill_parallel(species_mat, dist_mat, n_seeds, q_values, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kncn_single
IntegerVector cpp_kncn_single(IntegerMatrix species_pa, NumericVector x, NumericVector y, int seed);
RcppExport SEXP _spacc_cpp_kncn_single(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kncn_single(species_pa, x, y, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kncn_parallel
IntegerMatrix cpp_kncn_parallel(IntegerMatrix species_pa, NumericVector x, NumericVector y, int n_seeds, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_kncn_parallel(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kncn_parallel(species_pa, x, y, n_seeds, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kncn_kdtree_single
IntegerVector cpp_kncn_kdtree_single(IntegerMatrix species_pa, NumericVector x, NumericVector y, int seed, std::string distance);
RcppExport SEXP _spacc_cpp_kncn_kdtree_single(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kncn_kdtree_single(species_pa, x, y, seed, distance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kncn_kdtree_parallel
IntegerMatrix cpp_kncn_kdtree_parallel(IntegerMatrix species_pa, NumericVector x, NumericVector y, int n_seeds, int n_cores, bool progress, std::string distance);
RcppExport SEXP _spacc_cpp_kncn_kdtree_parallel(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kncn_kdtree_parallel(species_pa, x, y, n_seeds, n_cores, progress, distance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_single
IntegerVector cpp_knn_single(IntegerMatrix species_pa, NumericMatrix dist_mat, int seed);
RcppExport SEXP _spacc_cpp_knn_single(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_single(species_pa, dist_mat, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_parallel
IntegerMatrix cpp_knn_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_seeds, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_knn_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_parallel(species_pa, dist_mat, n_seeds, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_parallel_seeds
IntegerMatrix cpp_knn_parallel_seeds(IntegerMatrix species_pa, NumericMatrix dist_mat, IntegerVector seeds, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_knn_parallel_seeds(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_parallel_seeds(species_pa, dist_mat, seeds, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_kdtree_single
IntegerVector cpp_knn_kdtree_single(IntegerMatrix species_pa, NumericVector x, NumericVector y, int seed, std::string distance);
RcppExport SEXP _spacc_cpp_knn_kdtree_single(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_kdtree_single(species_pa, x, y, seed, distance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_kdtree_parallel
IntegerMatrix cpp_knn_kdtree_parallel(IntegerMatrix species_pa, NumericVector x, NumericVector y, int n_seeds, int n_cores, bool progress, std::string distance);
RcppExport SEXP _spacc_cpp_knn_kdtree_parallel(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_kdtree_parallel(species_pa, x, y, n_seeds, n_cores, progress, distance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_kdtree_parallel_seeds
IntegerMatrix cpp_knn_kdtree_parallel_seeds(IntegerMatrix species_pa, NumericVector x, NumericVector y, IntegerVector seeds, int n_cores, bool progress, std::string distance);
RcppExport SEXP _spacc_cpp_knn_kdtree_parallel_seeds(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_kdtree_parallel_seeds(species_pa, x, y, seeds, n_cores, progress, distance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_collector_single
IntegerVector cpp_collector_single(IntegerMatrix species_pa);
RcppExport SEXP _spacc_cpp_collector_single(SEXP species_paSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_collector_single(species_pa));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussian_single
IntegerVector cpp_gaussian_single(IntegerMatrix species_pa, NumericMatrix dist_mat, int seed, double sigma);
RcppExport SEXP _spacc_cpp_gaussian_single(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussian_single(species_pa, dist_mat, seed, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussian_parallel
IntegerMatrix cpp_gaussian_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_seeds, double sigma, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_gaussian_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP sigmaSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussian_parallel(species_pa, dist_mat, n_seeds, sigma, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_wavefront_single
List cpp_wavefront_single(IntegerMatrix species_pa, NumericMatrix dist_mat, int seed, double r0, double dr, int n_steps);
RcppExport SEXP _spacc_cpp_wavefront_single(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedSEXP, SEXP r0SEXP, SEXP drSEXP, SEXP n_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< double >::type dr(drSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_wavefront_single(species_pa, dist_mat, seed, r0, dr, n_steps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_wavefront_parallel
List cpp_wavefront_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_seeds, double r0, double dr, int n_steps, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_wavefront_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP r0SEXP, SEXP drSEXP, SEXP n_stepsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< double >::type dr(drSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_wavefront_parallel(species_pa, dist_mat, n_seeds, r0, dr, n_steps, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_radius_single
IntegerVector cpp_radius_single(IntegerMatrix species_pa, NumericMatrix dist_mat, int seed);
RcppExport SEXP _spacc_cpp_radius_single(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_radius_single(species_pa, dist_mat, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_radius_parallel
IntegerMatrix cpp_radius_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_seeds, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_radius_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_radius_parallel(species_pa, dist_mat, n_seeds, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cone_single
IntegerVector cpp_cone_single(IntegerMatrix species_pa, NumericVector x, NumericVector y, int seed, double angle, double width);
RcppExport SEXP _spacc_cpp_cone_single(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP seedSEXP, SEXP angleSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type angle(angleSEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cone_single(species_pa, x, y, seed, angle, width));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cone_parallel
IntegerMatrix cpp_cone_parallel(IntegerMatrix species_pa, NumericVector x, NumericVector y, int n_seeds, double width, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_cone_parallel(SEXP species_paSEXP, SEXP xSEXP, SEXP ySEXP, SEXP n_seedsSEXP, SEXP widthSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cone_parallel(species_pa, x, y, n_seeds, width, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_distance_decay_single
IntegerVector cpp_distance_decay_single(IntegerMatrix species_pa, NumericMatrix dist_mat, int seed, NumericVector breaks);
RcppExport SEXP _spacc_cpp_distance_decay_single(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP seedSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_distance_decay_single(species_pa, dist_mat, seed, breaks));
    return rcpp_result_gen;
END_RCPP
}
// cpp_distance_decay_parallel
IntegerMatrix cpp_distance_decay_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_seeds, NumericVector breaks, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_distance_decay_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_seedsSEXP, SEXP breaksSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_distance_decay_parallel(species_pa, dist_mat, n_seeds, breaks, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_knn_metrics_parallel
IntegerMatrix cpp_knn_metrics_parallel(IntegerMatrix species_pa, NumericMatrix dist_mat, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_knn_metrics_parallel(SEXP species_paSEXP, SEXP dist_matSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_knn_metrics_parallel(species_pa, dist_mat, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kncn_metrics_parallel
IntegerMatrix cpp_kncn_metrics_parallel(IntegerMatrix species_pa, NumericVector x_coords, NumericVector y_coords, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_kncn_metrics_parallel(SEXP species_paSEXP, SEXP x_coordsSEXP, SEXP y_coordsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_coords(x_coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_coords(y_coordsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kncn_metrics_parallel(species_pa, x_coords, y_coords, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// calc_mpd
double calc_mpd(NumericMatrix dist_mat, LogicalVector species_present, bool abundance_weighted, NumericVector abundances);
RcppExport SEXP _spacc_calc_mpd(SEXP dist_matSEXP, SEXP species_presentSEXP, SEXP abundance_weightedSEXP, SEXP abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type species_present(species_presentSEXP);
    Rcpp::traits::input_parameter< bool >::type abundance_weighted(abundance_weightedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mpd(dist_mat, species_present, abundance_weighted, abundances));
    return rcpp_result_gen;
END_RCPP
}
// calc_mntd
double calc_mntd(NumericMatrix dist_mat, LogicalVector species_present, bool abundance_weighted, NumericVector abundances);
RcppExport SEXP _spacc_calc_mntd(SEXP dist_matSEXP, SEXP species_presentSEXP, SEXP abundance_weightedSEXP, SEXP abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type species_present(species_presentSEXP);
    Rcpp::traits::input_parameter< bool >::type abundance_weighted(abundance_weightedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mntd(dist_mat, species_present, abundance_weighted, abundances));
    return rcpp_result_gen;
END_RCPP
}
// calc_faith_pd
double calc_faith_pd(IntegerMatrix edge, NumericVector edge_length, int n_tips, LogicalVector species_present);
RcppExport SEXP _spacc_calc_faith_pd(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipsSEXP, SEXP species_presentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type species_present(species_presentSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_faith_pd(edge, edge_length, n_tips, species_present));
    return rcpp_result_gen;
END_RCPP
}
// cpp_phylo_knn_single
List cpp_phylo_knn_single(IntegerMatrix species_pa, NumericMatrix site_dist_mat, NumericMatrix phylo_dist_mat, int seed, CharacterVector metrics, Rcpp::Nullable<IntegerMatrix> tree_edge, Rcpp::Nullable<NumericVector> tree_edge_length, int tree_n_tips);
RcppExport SEXP _spacc_cpp_phylo_knn_single(SEXP species_paSEXP, SEXP site_dist_matSEXP, SEXP phylo_dist_matSEXP, SEXP seedSEXP, SEXP metricsSEXP, SEXP tree_edgeSEXP, SEXP tree_edge_lengthSEXP, SEXP tree_n_tipsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type site_dist_mat(site_dist_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phylo_dist_mat(phylo_dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metrics(metricsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<IntegerMatrix> >::type tree_edge(tree_edgeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<NumericVector> >::type tree_edge_length(tree_edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type tree_n_tips(tree_n_tipsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_phylo_knn_single(species_pa, site_dist_mat, phylo_dist_mat, seed, metrics, tree_edge, tree_edge_length, tree_n_tips));
    return rcpp_result_gen;
END_RCPP
}
// cpp_phylo_knn_parallel
List cpp_phylo_knn_parallel(IntegerMatrix species_pa, NumericMatrix site_dist_mat, NumericMatrix phylo_dist_mat, int n_seeds, CharacterVector metrics, int n_cores, bool progress, Rcpp::Nullable<IntegerMatrix> tree_edge, Rcpp::Nullable<NumericVector> tree_edge_length, int tree_n_tips);
RcppExport SEXP _spacc_cpp_phylo_knn_parallel(SEXP species_paSEXP, SEXP site_dist_matSEXP, SEXP phylo_dist_matSEXP, SEXP n_seedsSEXP, SEXP metricsSEXP, SEXP n_coresSEXP, SEXP progressSEXP, SEXP tree_edgeSEXP, SEXP tree_edge_lengthSEXP, SEXP tree_n_tipsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type site_dist_mat(site_dist_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phylo_dist_mat(phylo_dist_matSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metrics(metricsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<IntegerMatrix> >::type tree_edge(tree_edgeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<NumericVector> >::type tree_edge_length(tree_edge_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type tree_n_tips(tree_n_tipsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_phylo_knn_parallel(species_pa, site_dist_mat, phylo_dist_mat, n_seeds, metrics, n_cores, progress, tree_edge, tree_edge_length, tree_n_tips));
    return rcpp_result_gen;
END_RCPP
}
// calc_fdis
double calc_fdis(NumericMatrix traits, LogicalVector species_present, NumericVector abundances);
RcppExport SEXP _spacc_calc_fdis(SEXP traitsSEXP, SEXP species_presentSEXP, SEXP abundancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type species_present(species_presentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abundances(abundancesSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_fdis(traits, species_present, abundances));
    return rcpp_result_gen;
END_RCPP
}
// calc_fric_approx
double calc_fric_approx(NumericMatrix traits, LogicalVector species_present);
RcppExport SEXP _spacc_calc_fric_approx(SEXP traitsSEXP, SEXP species_presentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type species_present(species_presentSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_fric_approx(traits, species_present));
    return rcpp_result_gen;
END_RCPP
}
// cpp_func_knn_single
List cpp_func_knn_single(IntegerMatrix species_mat, NumericMatrix site_dist_mat, NumericMatrix traits, int seed, CharacterVector metrics);
RcppExport SEXP _spacc_cpp_func_knn_single(SEXP species_matSEXP, SEXP site_dist_matSEXP, SEXP traitsSEXP, SEXP seedSEXP, SEXP metricsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_mat(species_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type site_dist_mat(site_dist_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metrics(metricsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_func_knn_single(species_mat, site_dist_mat, traits, seed, metrics));
    return rcpp_result_gen;
END_RCPP
}
// cpp_func_knn_parallel
List cpp_func_knn_parallel(IntegerMatrix species_mat, NumericMatrix site_dist_mat, NumericMatrix traits, int n_seeds, CharacterVector metrics, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_func_knn_parallel(SEXP species_matSEXP, SEXP site_dist_matSEXP, SEXP traitsSEXP, SEXP n_seedsSEXP, SEXP metricsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_mat(species_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type site_dist_mat(site_dist_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metrics(metricsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_func_knn_parallel(species_mat, site_dist_mat, traits, n_seeds, metrics, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_random_single
IntegerVector cpp_random_single(IntegerMatrix species_pa, IntegerVector order);
RcppExport SEXP _spacc_cpp_random_single(SEXP species_paSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_random_single(species_pa, order));
    return rcpp_result_gen;
END_RCPP
}
// cpp_random_parallel
IntegerMatrix cpp_random_parallel(IntegerMatrix species_pa, int n_seeds, int n_cores, bool progress);
RcppExport SEXP _spacc_cpp_random_parallel(SEXP species_paSEXP, SEXP n_seedsSEXP, SEXP n_coresSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type species_pa(species_paSEXP);
    Rcpp::traits::input_parameter< int >::type n_seeds(n_seedsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_random_parallel(species_pa, n_seeds, n_cores, progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spacc_cpp_beta_knn_single", (DL_FUNC) &_spacc_cpp_beta_knn_single, 4},
    {"_spacc_cpp_beta_knn_parallel", (DL_FUNC) &_spacc_cpp_beta_knn_parallel, 6},
    {"_spacc_calc_coverage", (DL_FUNC) &_spacc_calc_coverage, 1},
    {"_spacc_cpp_knn_coverage_single", (DL_FUNC) &_spacc_cpp_knn_coverage_single, 3},
    {"_spacc_cpp_knn_coverage_parallel", (DL_FUNC) &_spacc_cpp_knn_coverage_parallel, 5},
    {"_spacc_interpolate_at_coverage", (DL_FUNC) &_spacc_interpolate_at_coverage, 3},
    {"_spacc_cpp_distance_matrix", (DL_FUNC) &_spacc_cpp_distance_matrix, 3},
    {"_spacc_calc_hill_number", (DL_FUNC) &_spacc_calc_hill_number, 2},
    {"_spacc_cpp_knn_hill_single", (DL_FUNC) &_spacc_cpp_knn_hill_single, 4},
    {"_spacc_cpp_knn_hill_parallel", (DL_FUNC) &_spacc_cpp_knn_hill_parallel, 6},
    {"_spacc_cpp_kncn_single", (DL_FUNC) &_spacc_cpp_kncn_single, 4},
    {"_spacc_cpp_kncn_parallel", (DL_FUNC) &_spacc_cpp_kncn_parallel, 6},
    {"_spacc_cpp_kncn_kdtree_single", (DL_FUNC) &_spacc_cpp_kncn_kdtree_single, 5},
    {"_spacc_cpp_kncn_kdtree_parallel", (DL_FUNC) &_spacc_cpp_kncn_kdtree_parallel, 7},
    {"_spacc_cpp_knn_single", (DL_FUNC) &_spacc_cpp_knn_single, 3},
    {"_spacc_cpp_knn_parallel", (DL_FUNC) &_spacc_cpp_knn_parallel, 5},
    {"_spacc_cpp_knn_parallel_seeds", (DL_FUNC) &_spacc_cpp_knn_parallel_seeds, 5},
    {"_spacc_cpp_knn_kdtree_single", (DL_FUNC) &_spacc_cpp_knn_kdtree_single, 5},
    {"_spacc_cpp_knn_kdtree_parallel", (DL_FUNC) &_spacc_cpp_knn_kdtree_parallel, 7},
    {"_spacc_cpp_knn_kdtree_parallel_seeds", (DL_FUNC) &_spacc_cpp_knn_kdtree_parallel_seeds, 7},
    {"_spacc_cpp_collector_single", (DL_FUNC) &_spacc_cpp_collector_single, 1},
    {"_spacc_cpp_gaussian_single", (DL_FUNC) &_spacc_cpp_gaussian_single, 4},
    {"_spacc_cpp_gaussian_parallel", (DL_FUNC) &_spacc_cpp_gaussian_parallel, 6},
    {"_spacc_cpp_wavefront_single", (DL_FUNC) &_spacc_cpp_wavefront_single, 6},
    {"_spacc_cpp_wavefront_parallel", (DL_FUNC) &_spacc_cpp_wavefront_parallel, 8},
    {"_spacc_cpp_radius_single", (DL_FUNC) &_spacc_cpp_radius_single, 3},
    {"_spacc_cpp_radius_parallel", (DL_FUNC) &_spacc_cpp_radius_parallel, 5},
    {"_spacc_cpp_cone_single", (DL_FUNC) &_spacc_cpp_cone_single, 6},
    {"_spacc_cpp_cone_parallel", (DL_FUNC) &_spacc_cpp_cone_parallel, 7},
    {"_spacc_cpp_distance_decay_single", (DL_FUNC) &_spacc_cpp_distance_decay_single, 4},
    {"_spacc_cpp_distance_decay_parallel", (DL_FUNC) &_spacc_cpp_distance_decay_parallel, 6},
    {"_spacc_cpp_knn_metrics_parallel", (DL_FUNC) &_spacc_cpp_knn_metrics_parallel, 4},
    {"_spacc_cpp_kncn_metrics_parallel", (DL_FUNC) &_spacc_cpp_kncn_metrics_parallel, 5},
    {"_spacc_calc_mpd", (DL_FUNC) &_spacc_calc_mpd, 4},
    {"_spacc_calc_mntd", (DL_FUNC) &_spacc_calc_mntd, 4},
    {"_spacc_calc_faith_pd", (DL_FUNC) &_spacc_calc_faith_pd, 4},
    {"_spacc_cpp_phylo_knn_single", (DL_FUNC) &_spacc_cpp_phylo_knn_single, 8},
    {"_spacc_cpp_phylo_knn_parallel", (DL_FUNC) &_spacc_cpp_phylo_knn_parallel, 10},
    {"_spacc_calc_fdis", (DL_FUNC) &_spacc_calc_fdis, 3},
    {"_spacc_calc_fric_approx", (DL_FUNC) &_spacc_calc_fric_approx, 2},
    {"_spacc_cpp_func_knn_single", (DL_FUNC) &_spacc_cpp_func_knn_single, 5},
    {"_spacc_cpp_func_knn_parallel", (DL_FUNC) &_spacc_cpp_func_knn_parallel, 7},
    {"_spacc_cpp_random_single", (DL_FUNC) &_spacc_cpp_random_single, 2},
    {"_spacc_cpp_random_parallel", (DL_FUNC) &_spacc_cpp_random_parallel, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_spacc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
